import mongoose, { Schema, Document } from 'mongoose';

export interface IReminder extends Document {
  userId: mongoose.Types.ObjectId;
  emailId: mongoose.Types.ObjectId;
  gmailId: string;
  threadId: string;
  subject: string;
  followUpDate: Date;
  isCompleted: boolean;
  autoGenerated: boolean;
  draft?: string;
  createdAt: Date;
  updatedAt: Date;
}

const ReminderSchema = new Schema<IReminder>(
  {
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    emailId: { type: Schema.Types.ObjectId, ref: 'Email' },
    gmailId: { type: String, required: true },
    threadId: { type: String, required: true },
    subject: { type: String, required: true },
    followUpDate: { type: Date, required: true },
    isCompleted: { type: Boolean, default: false },
    autoGenerated: { type: Boolean, default: false },
    draft: String,
  },
  { timestamps: true }
);

ReminderSchema.index({ userId: 1, followUpDate: 1 });
ReminderSchema.index({ userId: 1, isCompleted: 1 });

export const Reminder = mongoose.model<IReminder>('Reminder', ReminderSchema);

